apiVersion: v1
kind: PersistentVolume
metadata:
  name: do-block-storage
  labels:
    name: do-block-storage
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
